version: 2

jobs:
    build:
        docker:
            - image: regviz/node-xcb

        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-npm-deps-{{ checksum "package-lock.json" }}
                      - v1-npm-deps-

            - run: npm ci

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}

            - run: npm run screenshot
            - run: npm run regression
