version: 2

jobs:
    vrt:
        docker:
            - image: regviz/node-xcb

        working_directory: ~/repo

        steps:
            - checkout
            - restore_cache:
              keys:
                  - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
                  - v1-dependencies-

            - run:
              name: npm install
              command: npm ci

            - save_cache:
              paths:
                  - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

            - run: npm run screenshot
            - run: npm run regression
