import { Story } from '@storybook/vue3';
import OPokemonStatusForm from '@/components/03-organisms/pokemon/status/o-pokemon-status-form/Index.vue';
import {
    AutoCompleteItem,
    SelectedItem
} from '@/components/03-organisms/pokemon/status/o-pokemon-status-form';

// More on default export: https://storybook.js.org/docs/vue/writing-stories/introduction#default-export
export default {
    title: 'Organisms/Pokemon/Status/o-pokemon-status-form',
    component: OPokemonStatusForm,
    // More on argTypes: https://storybook.js.org/docs/vue/api/argtypes
    argTypes: {
        autoCompleteItems: {
            name: 'autoCompleteItems',
            type: { name: 'array', required: false },
            defaultValue: [
                { id: 1, name: 'フシギダネ' },
                { id: 3, name: 'フシギソウ' },
                { id: 5, name: 'フシギバナ' },
                { id: 7, name: 'ヒトカゲ' },
                { id: 9, name: 'リザード' },
                { id: 11, name: 'リザードン' },
                { id: 13, name: 'ゼニガメ' },
                { id: 15, name: 'カメール' },
                { id: 17, name: 'カメックス' },
                { id: 19, name: 'キャタピー' },
                { id: 21, name: 'トランセル' },
                { id: 23, name: 'バタフリー' },
                { id: 25, name: 'ビードル' },
                { id: 27, name: 'コクーン' },
                { id: 29, name: 'スピアー' },
                { id: 31, name: 'ポッポ' },
                { id: 33, name: 'ピジョン' },
                { id: 35, name: 'ピジョット' },
                { id: 37, name: 'コラッタ' },
                { id: 39, name: 'ラッタ' },
                { id: 41, name: 'オニスズメ' },
                { id: 43, name: 'オニドリル' },
                { id: 45, name: 'アーボ' },
                { id: 47, name: 'アーボック' },
                { id: 49, name: 'ピカチュウ' },
                { id: 51, name: 'ライチュウ' },
                { id: 53, name: 'サンド' },
                { id: 55, name: 'サンドパン' },
                { id: 57, name: 'ニドラン♀' },
                { id: 59, name: 'ニドリーナ' },
                { id: 61, name: 'ニドクイン' },
                { id: 63, name: 'ニドラン♂' },
                { id: 65, name: 'ニドリーノ' },
                { id: 67, name: 'ニドキング' },
                { id: 69, name: 'ピッピ' },
                { id: 71, name: 'ピクシー' },
                { id: 73, name: 'ロコン' },
                { id: 75, name: 'キュウコン' },
                { id: 77, name: 'プリン' },
                { id: 79, name: 'プクリン' },
                { id: 81, name: 'ズバット' },
                { id: 83, name: 'ゴルバット' },
                { id: 85, name: 'ナゾノクサ' },
                { id: 87, name: 'クサイハナ' },
                { id: 89, name: 'ラフレシア' },
                { id: 91, name: 'パラス' },
                { id: 93, name: 'パラセクト' },
                { id: 95, name: 'コンパン' },
                { id: 97, name: 'モルフォン' },
                { id: 99, name: 'ディグダ' },
                { id: 101, name: 'ダグトリオ' },
                { id: 103, name: 'ニャース' },
                { id: 105, name: 'ペルシアン' },
                { id: 107, name: 'コダック' },
                { id: 109, name: 'ゴルダック' },
                { id: 111, name: 'マンキー' },
                { id: 113, name: 'オコリザル' },
                { id: 115, name: 'ガーディ' },
                { id: 117, name: 'ウインディ' },
                { id: 119, name: 'ニョロモ' },
                { id: 121, name: 'ニョロゾ' },
                { id: 123, name: 'ニョロボン' },
                { id: 125, name: 'ケーシィ' },
                { id: 127, name: 'ユンゲラー' },
                { id: 129, name: 'フーディン' },
                { id: 131, name: 'ワンリキー' },
                { id: 133, name: 'ゴーリキー' },
                { id: 135, name: 'カイリキー' },
                { id: 137, name: 'マダツボミ' },
                { id: 139, name: 'ウツドン' },
                { id: 141, name: 'ウツボット' },
                { id: 143, name: 'メノクラゲ' },
                { id: 145, name: 'ドククラゲ' },
                { id: 147, name: 'イシツブテ' },
                { id: 149, name: 'ゴローン' },
                { id: 151, name: 'ゴローニャ' },
                { id: 153, name: 'ポニータ' },
                { id: 155, name: 'ギャロップ' },
                { id: 157, name: 'ヤドン' },
                { id: 159, name: 'ヤドラン' },
                { id: 161, name: 'コイル' },
                { id: 163, name: 'レアコイル' },
                { id: 165, name: 'カモネギ' },
                { id: 167, name: 'ドードー' },
                { id: 169, name: 'ドードリオ' },
                { id: 171, name: 'パウワウ' },
                { id: 173, name: 'ジュゴン' },
                { id: 175, name: 'ベトベター' },
                { id: 177, name: 'ベトベトン' },
                { id: 179, name: 'シェルダー' },
                { id: 181, name: 'パルシェン' },
                { id: 183, name: 'ゴース' },
                { id: 185, name: 'ゴースト' },
                { id: 187, name: 'ゲンガー' },
                { id: 189, name: 'イワーク' },
                { id: 191, name: 'スリープ' },
                { id: 193, name: 'スリーパー' },
                { id: 195, name: 'クラブ' },
                { id: 197, name: 'キングラー' },
                { id: 199, name: 'ビリリダマ' },
                { id: 201, name: 'マルマイン' },
                { id: 203, name: 'タマタマ' },
                { id: 205, name: 'ナッシー' },
                { id: 207, name: 'カラカラ' },
                { id: 209, name: 'ガラガラ' },
                { id: 211, name: 'サワムラー' },
                { id: 213, name: 'エビワラー' },
                { id: 215, name: 'ベロリンガ' },
                { id: 217, name: 'ドガース' },
                { id: 219, name: 'マタドガス' },
                { id: 221, name: 'サイホーン' },
                { id: 223, name: 'サイドン' },
                { id: 225, name: 'ラッキー' },
                { id: 227, name: 'モンジャラ' },
                { id: 229, name: 'ガルーラ' },
                { id: 231, name: 'タッツー' },
                { id: 233, name: 'シードラ' },
                { id: 235, name: 'トサキント' },
                { id: 237, name: 'アズマオウ' },
                { id: 239, name: 'ヒトデマン' },
                { id: 241, name: 'スターミー' },
                { id: 243, name: 'バリヤード' },
                { id: 245, name: 'ストライク' },
                { id: 247, name: 'ルージュラ' },
                { id: 249, name: 'エレブー' },
                { id: 251, name: 'ブーバー' },
                { id: 253, name: 'カイロス' },
                { id: 255, name: 'ケンタロス' },
                { id: 257, name: 'コイキング' },
                { id: 259, name: 'ギャラドス' },
                { id: 261, name: 'ラプラス' },
                { id: 263, name: 'メタモン' },
                { id: 265, name: 'イーブイ' },
                { id: 267, name: 'シャワーズ' },
                { id: 269, name: 'サンダース' },
                { id: 271, name: 'ブースター' },
                { id: 273, name: 'ポリゴン' },
                { id: 275, name: 'オムナイト' },
                { id: 277, name: 'オムスター' },
                { id: 279, name: 'カブト' },
                { id: 281, name: 'カブトプス' },
                { id: 283, name: 'プテラ' },
                { id: 285, name: 'カビゴン' },
                { id: 287, name: 'フリーザー' },
                { id: 289, name: 'サンダー' },
                { id: 291, name: 'ファイヤー' },
                { id: 293, name: 'ミニリュウ' },
                { id: 295, name: 'ハクリュー' },
                { id: 297, name: 'カイリュー' },
                { id: 299, name: 'ミュウツー' },
                { id: 301, name: 'ミュウ' }
            ] as AutoCompleteItem[],
            description: 'autocomplete items'
        },
        defaultItems: {
            name: 'defaultItems',
            type: { name: 'array', required: false },
            defaultValue: [
                { id: 1, name: 'フシギダネ', canDelete: false, color: 'red' }
            ] as SelectedItem[],
            description: 'default items'
        }
    }
};

const Template: Story<any> = (args) => ({
    components: { OPokemonStatusForm },
    setup() {
        return { args };
    },
    template: '<o-pokemon-status-form v-bind="args"></o-pokemon-status-form>'
});

export const Simple = Template.bind({});
// More on args: https://storybook.js.org/docs/vue/writing-stories/args
Simple.args = {};
